#!/bin/bash 
#SBATCH -p lenovo
#SBATCH -t 3-00:00:00 
#SBATCH -N 1
#SBATCH -n 10

#SBATCH -J  LaH10_sscha_relaxation
#SBATCH -o  sscha_output
#SBATCH -e  error

module purge; source /path/to/miniconda3/bin/activate sscha 
python /path/to/sscha_relax_mtp_learn.py input_sscha.py
